package barrage.ir;

enum Opcode {
	WAIT;
	WAIT_SECONDS_CONST;
	WAIT_FRAMES_CONST;
	FIRE;
	FIRE_CONST;
	PROPERTY_SET;
	PROPERTY_SET_SPEED_CONST;
	PROPERTY_SET_DIRECTION_CONST;
	PROPERTY_SET_ACCEL_CONST;
	PROPERTY_TWEEN;
	PROPERTY_TWEEN_SPEED_CONST;
	PROPERTY_TWEEN_DIRECTION_CONST;
	PROPERTY_TWEEN_ACCEL_CONST;
	ACTION;
	ACTION_REF;
	DIE;
}
